[package]
name = "rust-demo"
version = "0.1.0"
authors = ["xiejinhua"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
systemstat = "https://github.com/unrelentingtech/systemstat"

[dependencies]
systemstat = "0.1.7"